First and second tasks
js-tasks-ru/js-20210309-2_marija-bolschakova pull request #1
Opened 2021-03-13 08:45 UTC by marijabolschakova

2021-03-14 14:28 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> + export function sortStrings(arr, param = 'asc') {
где-то это решение я видел...
поэтому вопрос: почему использован `switch...case`, какую проблему он решает?

2021-03-14 14:28 UTC, dosandk requested changes
необходимо дать ответ на вопрос

2021-03-15 09:57 UTC, marijabolschakova commented on 02-javascript-data-types/1-sort-strings/index.js
> + export function sortStrings(arr, param = 'asc') {
Определяет порядок направления сортировки

2021-03-16 20:31 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> + export function sortStrings(arr, param = 'asc') {
есть помимо `switch...case` множество других способов задать направление сортировки. Вопрос в том понимаете ли Вы преимущество использования `switch`

2021-03-16 20:31 UTC, dosandk approved these changes

2021-03-19 14:22 UTC, dosandk approved these changes

2021-03-22 10:19 UTC, dosandk approved these changes

2021-03-23 09:15 UTC, dosandk submitted a review, later dismissed

2021-03-23 13:29 UTC, dosandk approved these changes

2021-03-23 13:30 UTC, merged